"""profile_pic column added

Revision ID: 04433b15fecf
Revises: caabf917e453
Create Date: 2025-11-15 16:02:21.432829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04433b15fecf'
down_revision = 'caabf917e453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    # ### end Alembic commands ###
